# M3 T01

In [3]:
import numpy as np

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [6]:
def estadistiques(vector):
    if vector.ndim != 1:
        print("L'array ha de tenir una sola dimensió")
        return
    print(f"Array: {vector}")
    print(f"Mitjana: {np.mean(vector)}")
    print(f"Mediana: {np.median(vector)}")
    print(f"Valor mínim: {np.amin(vector)}")
    print(f"Valor màxim: {np.amax(vector)}")
    print(f"Rang: {np.ptp(vector)}")
    print(f"Variança: {np.var(vector)}")
    print(f"Desviació estàndart: {np.std(vector)}")
    
    

In [5]:
## Cel·la per provar la funciò anterior
estadistiques(np.array([5, 25, 9, 4, 30, 48, 12]))

Array: [ 5 25  9  4 30 48 12]
Mitjana: 19.0
Mediana: 12.0
Valor mínim: 4
Valor màxim: 48
Rang: 44
Variança: 224.0
Desviació estàndart: 14.966629547095765


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [10]:
def quadrat_aleatori(size):
    if not isinstance(size, int) or size < 0:
        print("El tamany ha de ser un enter positiu")
        return
    quadrat=np.random.randint(0, 100, (size, size))
    return quadrat

In [13]:
#Cel·la per a provar la funció
print(quadrat_aleatori(5))

[[ 8  6 25 11  4]
 [21 48 98 81 86]
 [30 10 18 77 91]
 [60 55 58 37 68]
 [92 35 92 50 18]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [12]:
def sumar_array(array):
    print(f"L'array proporcionada és:\n {array}")
    print(f"Els totals de les sumes per columna son {np.apply_along_axis(sum, 0, array)}")
    print(f"Els totals de les sumes per files són : {np.apply_along_axis(sum, 1, array)}")

In [13]:
# Cel·la per a provar la funció anterior
my_array=quadrat_aleatori(3)
sumar_array(my_array)

L'array proporcionada és:
 [[55 59 67]
 [67 19 60]
 [22 56 74]]
Els totals de les sumes per columna son [144 134 201]
Els totals de les sumes per files són : [181 146 152]


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [4]:
def coeficient_correlacio(array_x, array_y):
    sumatori_top=0
    sumx_bottom=0
    sumy_bottom=0
    mean_x=np.mean(array_x)
    mean_y=np.mean(array_y)
    for i in range(len(array_x)):
        sumatori_top+=(array_x[i] - mean_x) * (array_y[i] - mean_y)
    for element in array_x:
        sumx_bottom+=(element - mean_x) ** 2
    for element in array_y:
        sumy_bottom+=(element - mean_y) ** 2
    return sumatori_top / np.sqrt((sumx_bottom * sumy_bottom))

In [9]:
# Cel·la per provar la funciò anterior
array_x=np.array([5, 4 , 3])
array_y=np.array([4 , 12, 3])
print(f"El coeficient de correlació dels arrays\n x={array_x} i y={array_y}\n que has calculat és {coeficient_correlacio(array_x, array_y)}\n ")
#Comprovació del resultat
print(f"El coeficient de correlació correcte dels arrays\n x={array_x} i y={array_y}\n és {np.corrcoef(array_x, array_y)[0,1]}")

El coeficient de correlació dels arrays
 x=[5 4 3] i y=[ 4 12  3]
 que has calculat és 0.1013606067599229
 
El coeficient de correlació correcte dels arrays
 x=[5 4 3] i y=[ 4 12  3]
 és 0.1013606067599229
