# M3 T01

In [1]:
import numpy as np

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [6]:
def estadistiques(vector):
    if vector.ndim != 1:
        print("L'array ha de tenir una sola dimensió")
        return
    print(f"Array: {vector}")
    print(f"Mitjana: {np.mean(vector)}")
    print(f"Mediana: {np.median(vector)}")
    print(f"Valor mínim: {np.amin(vector)}")
    print(f"Valor màxim: {np.amax(vector)}")
    print(f"Rang: {np.ptp(vector)}")
    print(f"Variança: {np.var(vector)}")
    print(f"Desviació estàndart: {np.std(vector)}")
    
    

In [5]:
## Cel·la per provar la funciò anterior
estadistiques(np.array([5, 25, 9, 4, 30, 48, 12]))

Array: [ 5 25  9  4 30 48 12]
Mitjana: 19.0
Mediana: 12.0
Valor mínim: 4
Valor màxim: 48
Rang: 44
Variança: 224.0
Desviació estàndart: 14.966629547095765


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [7]:
def quadrat_aleatori(size):
    quadrat=np.random.randint(0, 100, (size, size))
    return quadrat

In [8]:
#Cel·la per a provar la funció
print(quadrat_aleatori(4))

[[11 40 52 97]
 [35 35 41 99]
 [99 71 67 24]
 [83 53 18 42]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [12]:
def sumar_array(array):
    print(f"L'array proporcionada és:\n {array}")
    print(f"Els totals de les sumes per columna son {np.apply_along_axis(sum, 0, array)}")
    print(f"Els totals de les sumes per files són : {np.apply_along_axis(sum, 1, array)}")

In [13]:
# Cel·la per a provar la funció anterior
my_array=quadrat_aleatori(3)
sumar_array(my_array)

L'array proporcionada és:
 [[55 59 67]
 [67 19 60]
 [22 56 74]]
Els totals de les sumes per columna son [144 134 201]
Els totals de les sumes per files són : [181 146 152]


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [ ]:
def coeficient_correlacio (array):
    

In [ ]:
# Cel·la per provar la funciò anterior
